cabal-version:      3.0
name:               representations
version:            0.1.0.0
synopsis:           Statically typed symmetry-respecting linear maps
license:            BSD-3-Clause
license-file:       LICENSE
author:             Reuben Cohn-Gordon
maintainer:         reubenharry@gmail.com
category:           Math
build-type:         Simple
extra-doc-files:    CHANGELOG.md
                    README.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Representations.Utils
        Representations.Group
        Representations.Group.SU2
        Representations.Group.ChargeEq
        Representations.Group.IrrepDecide
        Representations.Rep.Obj
        Representations.Rep.Tensor
        Representations.Rep.Singleton
        Representations.Rep.HomBlock
        Representations.Rep.Sectors
        Representations.Intertwiner
        Representations.Intertwiner.Pretty
        Representations.Intertwiner.Random
        Representations.Mor
        Representations.CG.SU2
        Representations.CG.U1
        Representations.CG.FSymbol
        Representations.CG.RSymbol
        Representations.Example.SU2Example
        Representations.Example.U1Example
    build-depends:
        base ^>=4.19.2.0,
        linearmap-category >= 0.6 && < 0.7,
        linearmap-hmatrix >= 0.1 && < 0.2,
        free-vector-spaces,
        lens,
        adjunctions,
        singletons,
        singletons-th ^>=3.3,
        transformers,
        random,
        linear,
        ieee754,
        vector-space,
        containers,
        constrained-categories,
        manifolds-core,
        QuickCheck,
        hmatrix,
        vector,
        vector-sized,
        indexed-list-literals,
        finite-typelits,
        ghc-typelits-knownnat,
        mtl
    hs-source-dirs:   src
    default-language: Haskell2010
